# Основная документация: https://github.com/dorny/paths-filter (см. всё к полю `filters`)

# Пути прописываются в виде picomatch-паттернов:
#   https://github.com/micromatch/picomatch#basic-globbing

# Можно использовать все фишки YAML-я:
#   https://ru.wikipedia.org/wiki/YAML#%D0%A1%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81

# Имена последних объектов (packages, lintable) лучше не менять

configs: &configs  # изменения тут обязательно запускают все пайплайны
  - ".github/workflows/*"
  - ".github/package-filters.yml"
  - "package.json"
  - ".npmrc"

lintable:  # запускает прогон линтера
  - *configs
  - "**/eslint.config.js"
  - "prettier.config.js"
  - "**.[jt]s"
  - "**.[jt]sx"
  - "**.md"

packages:  # запускает деплой @xipkg/calls-* в main-ветке (только обновлённых)
  - *configs
  - "packages/calls/**"
  - "packages/calls.*/**"
  - "tsup.calls.base.ts"
