#!/bin/bash
set -euo pipefail

# Only @xipkg/calls-* packages (publishable)
packages=$(ls -d packages/calls*/ 2>/dev/null | sort) || exit 0

echo "# autogenerated packages data" > "$filename"

for package in $packages; do
  dirname=${package%/*}
  dirname=${dirname#*/}
  key=${dirname//\//-}

  printf '%s:\n  - %s**\n' "$key" "$package" >> "$filename"
done

echo "saved filters to $filename"
